Runnect/Runnect-Android

app/src/main/java/com/runnect/runnect/data/dto/response/ResponseRecordInfo.kt
서버에서 null을 담아 보내주는 publicCourseId의 타입을 nullable로 해주지 않아 발생한 이슈 해결
#40 마이페이지 - 활동 기록 null 오류 처리
서버에서 null을 담아 보내주는 publicCourseId의 타입을 nullable로 해주지 않아 발생한 이슈 해결
=> Fix/36 마이페이지 - 활동 기록 null 오류 처리

app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt, app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt, app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverViewModel.kt, app/src/main/java/com/runnect/runnect/presentation/discover/adapter/CourseRecommendAdapter.kt
#51 코스추천 스크랩 이슈 해결
스크랩 -> 상세로 갔을 때에는 문제 없이 스크랩 여부가 뜨지만, 상세에서 스크랩 후 코스 발견으로 돌아오면 
적용이 안되어있는 문제 해결
==> registerForActivityResult를 활용하여 스크랩 후 다시 돌아올 때 getRecommendCourse()를 호출하도록 구현
=> Fix/51 코스추천 스크랩 이슈 해결

app/src/main/java/com/runnect/runnect/presentation/storage/StorageScrapFragment.kt
#54 최초 로딩 시 스크랩 목록 없을 때 대체 컴포넌트 띄우기
스크랩 data가 없을 때 최초 로딩 시에도 '스크랩하러가기' 버튼이 뜨도록 logic을 수정해주었음
=> #54 [Fix] 스크랩하러가기 logic 수정

app/src/main/java/com/runnect/runnect/data/api/KCourseService.kt, app/src/main/java/com/runnect/runnect/data/model/RequestPutMyDrawDto.kt, app/src/main/java/com/runnect/runnect/data/model/ResponsePutMyDrawDto.kt, app/src/main/java/com/runnect/runnect/presentation/MainActivity.kt, app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt, app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailViewModel.kt, app/src/main/java/com/runnect/runnect/presentation/report/ReportActivity.kt, app/src/main/java/com/runnect/runnect/presentation/storage/StorageMyDrawFragment.kt, app/src/main/java/com/runnect/runnect/presentation/storage/StorageViewModel.kt, app/src/main/java/com/runnect/runnect/presentation/storage/adapter/StorageMyDrawAdapter.kt, app/src/main/java/com/runnect/runnect/util/callback/DeleteMyDrawCourse.kt, app/src/main/res/drawable/shape_address_bar.xml, app/src/main/res/layout/fragment_storage_my_draw.xml, app/src/main/res/layout/fragment_storage_scrap.xml, app/src/main/res/layout/item_storage_my_draw.xml
#67 코스그리기보관함마감
- 스크랩 상세페이지 -> CountDown data 전달 (실수로 develop 브랜치에서 바로 작업해서 올려버렸음)
- 웹뷰 구현
- 내가그린코스 다중 삭제 구현
- 내가그린코스 상세페이지에서 삭제 시 보관함으로 이동하게 함
- 편집 버튼 터치 시 체크박스 띄우고 item 선택이 가능하게 함
- 선택된 item 개수를 화면에 표시
- 편집 가능 여부에 따라 버튼 enable 속성 조절 
- 화면 상단에 가이드뷰 (ex. 터치로 코스를 그려보세요) 추가
**1. 편집 버튼 터치 시 체크박스 띄우는 logic에 notifySetDataChanged()를 쓴 것**
ListAdapter를 사용하는만큼 submitList를 쓰고싶었으나 submitList를 쓸 경우 기능이 제대로 작동하지 않음.
개인적인 생각으로는 지금 짜놓은 DiffUtil이 data들의 id값을 비교해서 변화를 감지하는 식인데
편집 버튼 터치로 체크박스를 띄우는 상황은 data는 그대로인데 UI만 업데이트하는 거라 DiffUtil이 안 먹히는 것 같음.
그래서 변화 여부에 관계없이 그냥 전체를 새로 그려버리는 notifySetDataChanged()를 썼는데 아무래도 전체를 다시 그리는 거라 비효율적인 것 같아서 고민이 됨.  
**2. 내가그린코스 다중 삭제할 때마다 어댑터 초기화**
한 번 삭제하고나면 인덱스가 밀려서 isSelected도 제대로 적용 안 되고 인덱스 에러 떠서 앱도 죽길래 아예 삭제할 때마다 어댑터를 초기화하고 data도 매번 새로 받아와서 이런 문제 자체가 안 생기게 구현을 했음. 그런데 …
=> Feature/67 코스그리기보관함마감

app/src/main/java/com/runnect/runnect/data/dto/CourseDetailDTO.kt, app/src/main/java/com/runnect/runnect/data/dto/response/ResponseCourseDetail.kt, app/src/main/java/com/runnect/runnect/data/dto/response/ResponseUpdateNickName.kt, app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt, app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailViewModel.kt, app/src/main/java/com/runnect/runnect/presentation/discover/search/DiscoverSearchActivity.kt, app/src/main/java/com/runnect/runnect/presentation/discover/search/DiscoverSearchViewModel.kt, app/src/main/java/com/runnect/runnect/presentation/mypage/history/detail/MyHistoryDetailActivity.kt, app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadActivity.kt, app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadViewModel.kt, app/src/main/java/com/runnect/runnect/util/extension/ContextExt.kt, app/src/main/java/com/runnect/runnect/util/extension/ResponseExt.kt, app/src/main/res/layout/activity_course_detail.xml
#107 Response 관련 이슈 해결
- 출발지의 name이 null인 경우를 고려하여 Nullable로 수정
- 탈퇴한 회원의 경우 level이 Int가 아닌 "알 수 없음"이 와서 데이터가 올바르게 전달되지 않는 문제 해결 
-> level의 자료형을 문자열로 통일
- 업로드 및 활동기록 수정 완료 시 토스트 메시지 띄우기
- 닉네임 수정 Response 수정
- 업로드한 코스가 없을 때 반환형이 바뀌어버리는 이슈해결
- 코스발견-검색 시, 결과가 없는 경우 로직 수정
- Ui 수정
- 업로드한 코스가 없을 시, 업로드 하기로 이동하는 로직 추가
=> Fix/107 Response 관련 이슈 해결

app/src/main/java/com/runnect/runnect/presentation/MainActivity.kt, app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt, app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
#127 코스발견 - 스크랩 후 뒤로가기 시 미반영 이슈 해결
- 스크랩 또는 스크랩 취소 시에만 추천 코스를 다시 불러오도록 구현
- 기기 내 뒤로가기 클릭 시에도 유효하도록 구현
https://github.com/Runnect/Runnect-Android/assets/70442964/28bda6ec-6268-45f5-bd89-cb6a21b0e689
=> [Fix] 코스발견 - 스크랩 후 뒤로가기 시 미반영 이슈 해결

app/src/main/java/com/runnect/runnect/presentation/coursemain/CourseMainFragment.kt, app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt, app/src/main/res/layout/activity_draw.xml, app/src/main/res/layout/activity_end_run.xml, app/src/main/res/layout/activity_my_history_detail.xml, app/src/main/res/layout/activity_search.xml, app/src/main/res/layout/fragment_course_main.xml, app/src/main/res/layout/item_mypage_history.xml
#136 [fix] 거리/이동시간/평균페이스 표기하는 UI 간격 통일
투명한 박스를 3개 만들고 각각에 constraint를 걸고 width를 0dp로 주면 3개가 화면 가로 길이를 3등분하는데 이걸 이용해서 3등분된 박스 안에다 텍스트를 집어넣어주고 제약 조건을 걸어주었음.
=> #136 [fix] 거리/이동시간/평균페이스 표기하는 UI 간격 통일

app/src/main/res/layout/activity_my_history_detail.xml
지도의 크기때문에 디스플레이 높이가 낮은 기기에서는 일부 뷰가 잘려 보이는 문제 발생
#138 기록 상세 지도 이미지 조정
기록 상세 지도 이미지 조정
=> [Ui] 기록 상세 지도 이미지 조정

app/src/main/java/com/runnect/runnect/data/model/MyScrapCourse.kt, app/src/main/java/com/runnect/runnect/data/repository/StorageRepositoryImpl.kt, app/src/main/java/com/runnect/runnect/presentation/MainActivity.kt, app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt, app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt, app/src/main/java/com/runnect/runnect/presentation/storage/StorageMyDrawFragment.kt, app/src/main/java/com/runnect/runnect/presentation/storage/StorageScrapFragment.kt, app/src/main/java/com/runnect/runnect/presentation/storage/adapter/StorageScrapAdapter.kt
Fix/보관함 스크랩 통신에러
- 보관함 스크랩 통신 에러 해결
- 스크랩 상세페이지 백버튼 동작 추가
+)
보관함-스크랩에서 상세페이지로 넘어갔을 때 백버튼 logic에 추가가 안 돼있어서 작동이 안 되는 문제가 있었음. 추가해줘서 작동은 되나 getCourse 함수 호출이 안 돼서 일단 임시방편으로 MainActivity 이동 후 보관함으로 fragment replace가 되게 해주었음. 당장 안 해놓는 것보다는 낫지만 사용성이 떨어져서 추후 업데이트를 통해 해결해야 할 듯함.
또 지금 history 관리가 잘 안 되고 있음 백버튼 누르면 여기갔다 저기갔다 좀 엉망인데 날잡고 해결해야 할 듯함.
=> Fix/보관함 스크랩 통신에러

app/src/main/java/com/runnect/runnect/presentation/run/RunActivity.kt
#177 타이머 뒤로가기 시 stop 안 되는 이슈
제스쳐로 뒤로가기 시 onBackPressed()에 정의해준 stopTimer()가 적용 안 되었고, 해당 뷰에서 exit했는데도 timer가 계속 돌아서 리소스가 낭비되는 문제가 있었음. onDestroy에 stopTimer를 추가해줌으로써 문제를 해결하였음.
- onDestroy에 stopTimer 추가
=> #177 [fix] onDestroy에 stopTimer() 추가

app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
#181 코스 발견 배너 페이지 관련 이슈
파이어 베이스를 통해 배너 이미지를 삽입하게 되면서, 파이어 베이스에서 제공받는 이미지의 수와 고정되어있던 PAGE 수가 맞지 않아, 고정 PAGE 수가 초과하는 개수만큼의 빈 배너가 발생하는 이슈
=> 페이지 개수 고정값 FRAME_NUM을 vpList.size로 대체하여 해결
=> Fix/181 코스 발견 배너 페이지 관련 이슈

app/src/main/AndroidManifest.xml, app/src/main/java/com/runnect/runnect/data/dto/TimerData.kt, app/src/main/java/com/runnect/runnect/presentation/endrun/EndRunActivity.kt, app/src/main/java/com/runnect/runnect/presentation/run/RunActivity.kt, app/src/main/java/com/runnect/runnect/presentation/run/TimerService.kt, app/src/main/java/com/runnect/runnect/util/extension/DoubleExt.kt, app/src/main/res/layout/activity_run.xml
#180 service를 활용한 timer 이슈 해결
장시간 앱 이탈, 잠금화면 시 timer가 시간 반영이 제대로 안 된다거나 초기화 된다는 등의 문제를 보고 받았습니다. 기존에 백그라운드 동작에 대한 별 다른 조취가 없었던 것을 원인으로 파악하고 서비스를 활용하여 대응 작업을 해주었습니다.
<안드로이드-서비스-공식문서>
https://developer.android.com/guide/components/services?hl=ko
- timer 관련 logic을 TimerService로 분리
- memory leak이 발생하지 않게 생명주기를 고려하여 service 제거 코드 작성
서비스는 백그라운드에서 계속 도는 만큼 memory leak에 더욱 유의해야 한다고 생각하는데 서비스 사용이 처음이라 제가 중요한 부분을 놓쳤을 수 있습니다. 서비스 객체의 생성과 제거, 생명주기 쪽에서 안정적으로 잘 작업했는지 봐주시면 좋을 것 같습니다!
=> Refactor/180 timer service 적용

app/build.gradle, app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt, app/src/main/res/layout/fragment_discover.xml, app/src/main/res/layout/item_discover_course_info_shimmer.xml
#189 스켈레톤 ui 적용
ux 개선 목적으로 로딩 시 스켈레톤 ui를 적용해주었습니다.
로딩이 엄청 짧은 ui는 스켈레톤을 적용하는 게 오히려 거슬릴 것 같다는 아래 포스팅 내용에 공감하여 
코스 추천에만 적용시켜주었습니다.
https://tech.kakaopay.com/post/skeleton-ui-idea/
- 코스발견-코스추천 로딩 시 프로그레스바 -> 스켈레톤 ui로 교체했습니다.
- 스켈레톤으로 띄울 frame은 어떻게 짜든 상관없었는데 기존에 item_discover_course_info.xml를 최대한 재활용하는 방향으로 만들었습니다.
https://github.com/Runnect/Runnect-Android/assets/89737271/2f7cc917-ec08-4707-9e0d-82aada051841
=> Feature/189 skelton UI 적용

app/src/main/java/com/runnect/runnect/presentation/run/TimerService.kt
#198 timer '분' 셋째자리까지 표기되는 이슈가 있어 대응 작업을 해주었습니다.
timer '분' logic 수정
before)
val minute = time / 60
after)
val minute = (time % 3600) / 60
=> #198 [fix] timer minute logic 수정

app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
#206 코스발견에서 빠르게 다른 fragment menu로 전환 시 앱이 죽는 이슈
timerTask 객체가 delay(600) 뒤에 생성되는데 그 전에 다른 fragment로 menu를 전환하면 생성되지도 않은 timerTask를 cancel하려는 것이니 NPE가 뜹니다.
여기 배너 timer 관련 코드는 지훈이가 이번주에 개인 일정 끝내고 fix를 해주기로 했는데 그 전에 임시로 delay(700)을 주어 앱이 죽지 않게 조치를 취해놨습니다.
추후 timer 관련 코드 수정 후 코루틴을 사용하여 비동기적으로 처리되는 logic들 간의 순서를 맞춰주면 될 것 같습니다.
=> #206 [fix] 코스발견에서 빠르게 다른 fragment menu로 전환 시 앱이 죽는 이슈

app/src/main/java/com/runnect/runnect/data/service/TokenAuthenticator.kt, app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt, app/src/main/res/values/strings.xml
#209 코스발견 상단 배너 스크롤 타이머 로직 수정2
상단 배너 초기화 로직인 setPromotion 메소드가 비대해짐에 따라 발생한 비효율적인 로직 개선
배너 자동 스크롤에 사용되는 timer 및 timerTask의 초기화 관련 이슈 해결
- 초기화 로직과 비즈니스 로직의 분리
- 메소드 명 변경 setPromotion -> setPromotionBanner
- timer 및 timerTask의 초기화 여부에 따른 예외처리
번외 : Toast 메시지 표시가 UI Thread에서 이루어지도록 수정
=> Fix/209 코스발견 상단 배너 스크롤 타이머 로직 수정2

app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
#215 viewPage에 할당된 pageChangeCallback을 생명주기에 따라 unRegister 해줌으로써 fragment 전환 시 발생하는 메모리 누수 해결
-  callback 변수 분리
-  unregisterOnPageCallback 메소드 호출
https://github.com/Runnect/Runnect-Android/assets/70442964/a24585b5-25ae-42b6-bf9f-e2f82b7ae18e
=> [chore] unregisterPageChangeCallback 메소드 호출 추가

app/src/main/res/layout/item_mypage_history.xml, app/src/main/res/values/colors.xml
closed #237 마이페이지-러닝기록 / 이미지뷰 elevation 제거
- cardView elevation 제거
- MaterialCardView로 변경
- strokeColor, strokeWidth 추가
모서리 둥글게 imageView의 frame을 만들고 이 안에 서버에서 받아온 image data를 바인딩할 때 cardView 말고 더 간편한 방법이 있을까요?!
=> [fix] 마이페이지-러닝 기록 / 이미지뷰 elevation 제거

app/src/main/java/com/runnect/runnect/presentation/storage/StorageMainFragment.kt, app/src/main/res/layout/fragment_storage_main.xml
closed #249 [FIX] 보관함 / TabLayout 밑줄 수정 (색상, elevation)
- 명확한 원인 파악은 못했지만 elevation을 조절해주니 해결됐음
- underLine color G3 -> G4
왼쪽 이미지: 이번에 pr 올리는 코드
우측 이미지: 피그마 디자인 요구 사항
디자인 요구는 회색 underLine 바로 위를 보라색 밑줄이 덮는 건데 그렇게 못해냈습니다.
자세히 보시면 왼쪽은 덮는 게 아니라 위에 쌓여있습니다.
회색줄이 보라색줄을 덮고있으므로 보라색줄(tabLayout) elevation을 더 높게 주었더니 tabLayout 전체의 elevation이 높아져서 회색줄 자체를 아예 안 보이게 덮어버립니다. 그래서 elevation은 똑같이 맞춰주었고 대신 보라색줄 2dp중 1dp만큼을 회색줄이 덮어버리기 때문에 보정으로 보라색줄을 3dp로 설정해주었습니다 (3dp-1dp=2dp)
엄청 얇기 때문에 사실 말 안 하면 모를 이슈이긴 한데 그래도 일단 요구대로 온전히 구현해내지 못했으니 이슈 공유 해봅니다!
혹시 제가 놓친 부분이 있을까요?
=> [FIX] 보관함 / TabLayout 밑줄 안 뜨는 버그

app/src/main/java/com/runnect/runnect/presentation/search/SearchActivity.kt, app/src/main/java/com/runnect/runnect/presentation/search/SearchViewModel.kt, app/src/main/res/layout/activity_search.xml
closed #251 [DEL] 불필요한 onTextChanged 관련 코드 제거
editText에 입력값이 잘 들어가는지 모니터링 목적으로 xml에 onTextChanged를 달아놨는데 현시점에서는 binding.etSearch.text.toString()으로 값을 받아와 통신 함수 인자에 넣어주는 만큼 불필요해졌다 판단하여 제거합니다.
- xml 상에서 불필요하게 searchViewModel의 리소스를 참조하고 있던 것을 제거
- 뷰모델 searchKeyword 변수 제거
- 통신 함수에 인자로 전달하는 값을 binding.etSearch.text.toString()으로 대체
=> [DEL] 출발지 검색 / 불필요한 onTextChanged 관련 코드 제거

app/src/main/java/com/runnect/runnect/data/service/ReverseGeocodingService.kt, app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt, app/src/main/java/com/runnect/runnect/presentation/run/RunActivity.kt
closed #252 [MOD] 러닝 페이지 / 마커 리소스 수정
기존엔 정보창을 포함한 이미지를 svg로 뽑아 활용했었는데 커스텀 출발지를 구현하려면 무조건 infoWindow를 사용해야 했고 이를 위해선 기존의 방식을 버려야 했습니다. 따라서 지금 올리는 PR은 infoWindow를 활용하는 방향으로 코드를 수정해준 것입니다. (* infoWindow란 마커 위에 띄우는 정보창(말풍선)을 말합니다.)
+) 최근에 merge한 브랜치 병합 과정에서 conflict가 있었고 이를 풀어주는 과정에서 사용하지 않는 소스를 지우지 않아 build 에러가 떴습니다. 이 브랜치 merge 하고나면 해당 문제는 해결됩니다!
- infoWindow 활용
- PointF 수정
- build 오류 해결
=> [MOD] 러닝 페이지 / 마커 리소스 수정

app/src/main/java/com/runnect/runnect/presentation/mypage/history/detail/MyHistoryDetailActivity.kt, app/src/main/java/com/runnect/runnect/presentation/mypage/history/detail/MyHistoryDetailViewModel.kt
- closed #268
- 이슈 내용 참고 부탁드립니다! 
뷰모델을 이용해서 액티비티 생명주기와 무관하게 데이터들을 저장할 수 있다는 건 좋은데,
그에 따라 뷰모델에 getter, setter 관련 코드량이 증가한 것은 그닥 좋은 거 같지 않습니다..! 
더 나은 방법이 있을까요?!
=> [REFACTOR] 마이페이지 러닝기록 상세페이지 / 액티비티의 전역변수를 뷰모델로 이전

app/src/main/java/com/runnect/runnect/data/service/UserService.kt, app/src/main/java/com/runnect/runnect/presentation/mypage/history/detail/MyHistoryDetailActivity.kt, app/src/main/res/layout/activity_my_history_detail.xml
- closed #270 
- 이슈 내용 확인 부탁드립니다! 
굉장히 사소하지만 이런 걸로도 사용자 경험이 개선될 수 있다고 느꼈습니다! 
코드 변경 사항 얼마되지 않으니 빠른 확인 부탁드립니다 :) 
좋은 코드가 무엇인가를 고민하다가 개발 속도가 너무 더뎌지는 거 같아서, 이제는 좀 속도를 내보려고 합니다!!
데드라인 맞추는 것도 타 파트와의 협업에서 굉장히 중요하니까요! 
그리고 이번 이슈처럼 자잘한 것들도 계속해서 개선해나가겠습니다! 화이팅!
=> [CHORE] 마이페이지 러닝기록 / 제목 수정 시, 키보드 완료 버튼 누르면 바로 수정되도록 변경

app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt, app/src/main/java/com/runnect/runnect/util/DepartureSetMode.kt
closed #260 출발지 모드 세팅 / Enum Class 활용
- 매직 리터럴 -> Enum Class 
- 생성한 Enum Class 파일을 우선 Util에 넣어놨는데 어떤 폴더에서 관리하는 것이 적절할지 고민이 됩니다.
- 보통 Enum Class는 가독성 목적으로 많이 쓰는 것으로 알고 있는데 이전과 비교해서 가독성이 높아진 것 같나요?! 저는 체감이 잘 안 돼서 혹시 Enum Class를 더 효과적으로 쓸 수 있는 방법이 있을지 궁금합니다. 
- 단순히 매직 리터럴을 지양하려는 목적이라면 Enum Class 말고 companion object에 상수를 만들어서 쓰는 방법이랑 큰 차이가 없는 것 같은데 어떤 부분이 다르다고 생각하시나요?
=> [REFACTOR] 출발지 모드 세팅 / Enum Class 활용

app/src/main/java/com/runnect/runnect/data/service/ReverseGeocodingService.kt, app/src/main/java/com/runnect/runnect/data/service/TokenAuthenticator.kt
#254 [FIX] 토큰 갱신 / 로그인 페이지 이동 logic 배치 조정
2시간마다 일괄적으로 로그인 페이지로 이동하게 logic이 짜여져 있어서 해당 부분을 onFailure로 옮겨놓았고 현재 accessToken 만료 시 로그인 재요청 없이 정상적으로 갱신되는 것을 확인하였습니다.
현재의 코드로 refreshToken 만료 여부까지 확인해보고 만약 만료 시 로그인 페이지로 이동하지 않는다면 if문을 onSuccess 안에 배치하는 것으로 수정할 예정입니다.
- 로그인 페이지 이동 logic 배치 조정
로그인 페이지로 이동시키는 logic을 onSuccess에 넣어야 할지, onFailure에 넣어야 할지 헷갈립니다.
=> [FIX] 토큰 갱신 / 로그인 페이지 이동 logic 배치 조정

app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
closed #276
- 코스 제목 입력 후 완성하기 버튼 누르면 키보드 내리기
말씀해주셨던 동작이 아래 영상과 같을까요? 다르다면 알려주세요! 반영하겠습니다!
https://github.com/Runnect/Runnect-Android/assets/89737271/48589625-fd34-4a78-a2cc-5222bc5c1d95
=> [FEAT] 코스 그리기 / 코스 제목 입력 후 키보드 내리기

app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt, app/src/main/java/com/runnect/runnect/util/extension/ActivityExt.kt
closed #253
- 보관함으로 뒤로가기 및 코스 삭제 시 애니메이션 통일
=> [MOD] 상세페이지 / 보관함으로 뒤로가기 및 코스 삭제 시 애니메이션 통일

app/src/main/java/com/runnect/runnect/presentation/mypage/history/MyHistoryActivity.kt, app/src/main/java/com/runnect/runnect/presentation/mypage/history/MyHistoryViewModel.kt, app/src/main/res/layout/activity_my_history.xml
closed #265 
- 기존에 버튼이 TextView로 만들어져있던 걸 다 들어내고 Button으로 다시 만들어주었음
- 버튼 활성화 안 됐던 문제 해결
같은 기능을 보관함에서 구현한 코드가 있는데 여기는 제가 짠 코드가 아니라 일단 디버깅만 해놓고 추후에 제가 보관함에 짜놓은 스타일로 리팩토링을 할 예정입니다. 따라서 특별히 봐주실 부분은 없습니다!
https://github.com/Runnect/Runnect-Android/assets/89737271/9fa40d90-4b9f-4d97-af0e-1aa60e6443ab
=> [FIX] 러닝 기록 / 삭제 버튼 활성화 오류

app/src/main/java/com/runnect/runnect/presentation/run/RunActivity.kt, app/src/main/java/com/runnect/runnect/presentation/run/TimerService.kt
closed #273
- setOnlyAlertOnce(true) 추가를 통해 소리/진동 최초 1회로 제한
- 가독성을 위해 Service 파일 내 함수 배치 조정
- 당시 service 활용이 처음이라 정확히 알고 개발한 feature가 아니어서 코드적으로 불필요하거나 허술한 부분이 있을 수 있습니다. 혹시 그런 부분이 보인다면 피드백 부탁드립니다! 이 branch로 checkout해서 안드로이드 스튜디오에서 봐주시면 감사하겠습니다! (즉, **service를 잘 활용한 것이 맞는지**)
- 실 기기로 빌드 돌려서 어떤 문제(1초마다 시스템 알림소리/진동이 계속 울림)였는지 확인 후 지금 pr 올린 branch로 checkout해서 **문제가 잘 해결되었는지 테스트** 부탁드립니다!
- 공식 문서를 참고하여 당장 눈에 보이는 문제는 해결하긴 했는데 아래 스크린샷 보시면 매초마다 NotificationManager 로그가 계속 찍혀나옵니다. 원래 이게 당연한 건지, 아니면 제가 뭘 잘못해놔서 **불필요하게 리소스가 낭비**(ex. 함수나 객체 계속 호출)되고 있는지  잘 모르겠습니다. 혹시 이 부분 관련하여 피드백 받아볼 수 있으면 부탁드립니다!
https://developer.android.com/training/notify-user/build-notification?hl=ko#Updating
=> [FIX] setOnlyAlertOnce 추가를 통한 소리/진동 제한

app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt, app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverViewModel.kt, app/src/main/java/com/runnect/runnect/presentation/discover/adapter/BannerAdapter.kt, app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverMultiViewAdapter.kt, app/src/main/java/com/runnect/runnect/presentation/run/RunActivity.kt, app/src/main/java/com/runnect/runnect/presentation/run/TimerService.kt, app/src/main/java/com/runnect/runnect/util/extension/FragmentExt.kt, app/src/main/res/layout/fragment_discover.xml
- closed #286 
-  뷰페이저 무한 스크롤
-  인디케이터 같이 움직이도록
-  뷰페이저 스크롤 상태에 따라 Job 조정하기
-  상세페이지 갔다가 메인 돌아왔을 때 제목, 스크랩 변경사항 바로 반영하기 (아직 진행 중) 
코루틴의 delay 함수와 Job 객체의 생성/취소를 이용하여, 배너가 수평으로 무한 스크롤 되도록 구현했습니다! 
[이 블로그](https://bumjae.tistory.com/65#Infinite%20Scroll%20(%EB%AC%B4%ED%95%9C%20%EC%8A%A4%ED%81%AC%EB%A1%A4)-1)에 나와있는 방법을 많이 참고했어요! 
배너가 항상 같은 방향으로 스크롤 되어야 하기 때문에, 초기 위치를 `Int.MAX_VALUE / 2` 로 잡고 시간에 따라 또는 사용자의 터치 이벤트에 따라 뷰페이저 position이 +/- 되는 방식으로 구현했어요! 
코드 보다가 이해가 안 되는 부분은 질문 남겨주세요!!
=> [REFACTOR] 코스 발견 / 프로모션 배너 뷰페이저 애니메이션 

app/src/main/java/com/runnect/runnect/data/dto/response/ResponsePostMyDrawCourse.kt, app/src/main/java/com/runnect/runnect/data/repository/CourseRepositoryImpl.kt, app/src/main/java/com/runnect/runnect/data/service/CourseService.kt, app/src/main/java/com/runnect/runnect/data/source/remote/RemoteCourseDataSource.kt, app/src/main/java/com/runnect/runnect/domain/repository/CourseRepository.kt, app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt, app/src/main/java/com/runnect/runnect/presentation/draw/DrawViewModel.kt
- Closed #306 
- 코스 생성 api 수정 사항 반영 
- requestBody 및 response 수정 
- 출발지 설정 3개 mode에 대해 각각에 필요한 형태로 requestBody 및 putExtra 세팅 
- 버그 대응
- 커스텀 출발지 지정 : CountDownActivity로 data를 넘길 때 departureLatLng이 사용자가 지정한 출발지가 아닌 현위치 좌표값이 넘어가는 이슈
커스텀 출발지에서 사용자가 출발지를 직접 지정한 후에도(더이상 현위치 좌표값이 필요없는 상황에서도) addOnLocationChangeListener가 자동으로 계속 돌아서 departureLatLng을 현위치로 갱신시키는 바람에 
그러지 못하도록 isBlockUpdateDeparture라는 변수를 선언해서 사용자가 출발지를 직접 지정한 후에는 departureLatLng이 addOnLocationChangeListener에 의해 갱신이 못되도록 막아주었습니다.
그런데 (정확한 원인 파악은 못했지만 아마도) addOnLocationChangeListener는 실행 타이밍이 불규칙하다보니 제가 한 조치로는 온전히 막을 수 없는 것 같아 
사용자가 출발지를 직접 지정하는 시점에 customDepartureLatLng라는 변수를 따로 두어 putExtra 시점에 departureLatLng 값을 customDepartureLatLng으로 갱신시키는 방법으로 막았습니다.
문제 해결은 어찌저찌 했지만 코드가 깔끔하지 못하고 지저분해진다는 느낌에 아쉬움이 남습니다.
이번에 2차 업데이트(출발지 설정할 수 있는 옵션 …
=> [FEAT] 코스 생성 api 수정 사항 반영 및 버그 대응

app/src/main/java/com/runnect/runnect/data/repository/CourseRepositoryImpl.kt, app/src/main/java/com/runnect/runnect/data/service/CourseService.kt, app/src/main/java/com/runnect/runnect/data/source/remote/RemoteCourseDataSource.kt, app/src/main/java/com/runnect/runnect/domain/repository/CourseRepository.kt, app/src/main/java/com/runnect/runnect/presentation/MainActivity.kt, app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt, app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverViewModel.kt, app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverMarathonAdapter.kt, app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverRecommendAdapter.kt, app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewAdapter.kt, app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewHolder.kt, app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewHolderFactory.kt, app/src/main/java/com/runnect/runnect/util/extension/ContextExt.kt
closed #307 
이슈에 자세한 내용 기록해두었습니다! 
외부 리사이클러뷰 어댑터에서 내부 리사이클러뷰 뷰홀더의 bind 함수에 추천코스 리스트를 넘겨주는 부분이 있는데, 이때 깊은 고민 없이 리스트를 '얕은 복사' 하면서 예기치 못한 문제가 발생했습니다. 현재는 다음과 같이 코드를 수정했어요. 
```kotlin
override fun onBindViewHolder(holder: DiscoverMultiViewHolder, position: Int) {
when (holder) {
is DiscoverMultiViewHolder.MarathonCourseViewHolder -> {
holder.bind(marathonCourses)
}
is DiscoverMultiViewHolder.RecommendCourseViewHolder -> {
// 이렇게 리스트를 '얕은 복사'해서 넘기면 
// 내부 리사이클러뷰에서 submitList 하기 전에 
// 이미 외부 리사이클러뷰의 리스트와 데이터가 동일해짐. 
holder.bind(recommendCourses)
}
}
}
```
```kotlin
override fun onBindViewHolder(holder: DiscoverMultiViewHolder, position: Int) {
when (holder) {
is DiscoverMultiViewHolder.MarathonCourseViewHolder -> {
holder.bind(marathonCourses)
}
is …
```
=> [FEAT] 코스 발견 / 추천 코스 정렬 기능 

app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverMarathonAdapter.kt, app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverRecommendAdapter.kt, app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewAdapter.kt
- closed #324 
저번 회의 때 외부 리사이클러뷰 어댑터에서는 마라톤, 추천코스 데이터 목록을 쥐고 있지 말자는 얘기가 나왔습니다. 이 데이터 목록들은 내부에 있는 각각의 리사이클러뷰 어댑터에서 처리를 해주는 것이 맞기 때문입니다. 그래서 외부 리사이클러뷰를 처음 초기화 할 때만 사용하는 방식으로 변경했습니다. 
그런데 이때 외부 리사이클러뷰 어댑터의 스크랩 함수에서도 이 데이터 목록들을 사용하고 있다는 것을 깜박하여,,, 해당 부분까지 구현하여 다시 pr 올립니다. 저번에 더 꼼꼼히 확인했어야 했는데 이제야 발견해서 죄송합니다 🥹
이쪽 어댑터에서도 for문으로 아이템 탐색하는 것보다, 클릭한 아이템의 position 값을 어댑터에 저장해두는 게 나을까요?? 그러면 로딩 상태일 때는 [이때](https://github.com/Runnect/Runnect-Android/pull/320#discussion_r1489472416) 논의한 것과 마찬가지로 로딩 프로그레스바를 띄우는 등의 처리가 필요할 거 같습니다.
=> [FIX] 코스 발견 / 스크랩 함수의 로직 수정 

app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
- closed #331 
- CourseDetail에서 돌아갈 시, 기존 로직이 업로드한 코스 화면을 재생성해 스택에 두번쌓이는 문제 해결
=> [FIX] 마이페이지 / 업로드한 코스 재생성 문제 해결

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/runnect/runnect/data/service/TokenAuthenticator.kt, app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
- closed #228 
- interceptor 토큰 clear 로직 수정
- 카카오 sdk 공유 코드 제거
- 파이어베이스 동적 링크로 코스 공유 기능 구현 (iOS 호환 / 앱 미설치 시 플레이스토어 이동 테스트 완료)
-
https://github.com/Runnect/Runnect-Android/assets/89737271/02ca35bd-f49a-4c55-884e-5d3b16de49cb
=> [FEAT] 코스 상세 페이지 / Firebase 동적 링크로 코스 공유 구현

app/src/main/java/com/runnect/runnect/data/dto/UserUploadCourseDTO.kt, app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt, app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt, app/src/main/java/com/runnect/runnect/presentation/discover/model/EditableDiscoverCourse.kt, app/src/main/java/com/runnect/runnect/presentation/discover/search/DiscoverSearchActivity.kt, app/src/main/java/com/runnect/runnect/presentation/discover/upload/DiscoverUploadActivity.kt, app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadActivity.kt, app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadViewModel.kt, app/src/main/java/com/runnect/runnect/presentation/mypage/upload/adapter/MyUploadAdapter.kt
- closed #330 
코스 상세페이지에서 본인이 업로드한 코스인 경우, 수정/삭제가 가능합니다. 상세페이지에서 이런 변경사항이 발생했을 때, 이전 화면에 바로 반영되도록 구현했습니다. 
- 코스 발견: DiscoverFragment, DiscoverMultiViewAdapter
- 코스 검색: DiscoverSearchActivity, DiscoverSearchAdapter
- 마이페이지 내가 업로드한 코스: MyUploadActivity, MyUploadAdapter  
```kotlin
private fun navigateToPreviousScreen() {
if (isFromDeepLink) {
navigateToMainScreenWithBundle()
isFromDeepLink = false
return
}
when (rootScreen) {
COURSE_STORAGE_SCRAP -> MainActivity.updateStorageScrapScreen()
COURSE_DISCOVER -> setActivityResult<MainActivity>()
COURSE_DISCOVER_SEARCH -> setActivityResult<DiscoverSearchActivity>()
MY_PAGE_UPLOAD_COURSE -> setActivityResult<MyUploadActivity>()
}
finish()
overridePendingTransition(R.anim.slide_in_left, R.anim.slide_out_right)
}
private inline fun <reified E : …
```
=> [FIX] 코스 상세페이지 / 이전 화면으로 돌아갔을 때 변경사항 바로 반영되도록 

app/src/main/java/com/runnect/runnect/data/dto/UploadLatLng.kt
- Closed #350  
코스 생성 시 requestBody에 넣어주는 좌표값 변수명 변경
변수명이 다르니 서버로 값 올릴 때 path 값이 0.0으로 잘못 들어가는 버그가 있었음.
=> [fix] #350 코스 생성 시 requestBody에 넣어주는 좌표값 변수명 변경

app/build.gradle, app/src/main/java/com/runnect/runnect/data/dto/CourseData.kt, app/src/main/java/com/runnect/runnect/data/dto/RunToEndRunData.kt, app/src/main/java/com/runnect/runnect/data/dto/SearchResultEntity.kt, app/src/main/java/com/runnect/runnect/data/dto/TimerData.kt, app/src/main/java/com/runnect/runnect/domain/entity/DiscoverUploadCourse.kt, app/src/main/java/com/runnect/runnect/domain/entity/MyDrawCourse.kt, app/src/main/java/com/runnect/runnect/domain/entity/MyScrapCourse.kt, app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt, app/src/main/java/com/runnect/runnect/presentation/mypage/history/MyHistoryActivity.kt, app/src/main/java/com/runnect/runnect/presentation/mypage/setting/accountinfo/MySettingAccountInfoFragment.kt, app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadActivity.kt, app/src/main/java/com/runnect/runnect/presentation/storage/StorageMyDrawFragment.kt, app/src/main/java/com/runnect/runnect/util/extension/ContextExt.kt
- closed #285 
- kotlin-android-extensions 를 제거하고 parcelize 플러그인 추가
- viewBinding으로 기존의 익스텐션 대체
이제 컴포즈 버전업하면 될 것 같습니다 ~! 기존 다이얼로그 동작 잘되나 다 확인하긴 했는데 그래도 한번씩 실행부탁드려요 
그리고 기존 contextExt 로직을 유지하는 선에서 딱 제거작업만 해서 findViewById와 같은 개선할만한 사항이 남아있긴 합니다 컴포즈로 이전할 예정이라서 개선없이 그냥 두었어요 : )
=> [REFACTOR] kotlin-android-extensions 제거 후 viewBinding, kotlinx-parcelize 도입

app/build.gradle, app/src/main/java/com/runnect/runnect/presentation/coursemain/CourseMainFragment.kt, app/src/main/res/layout/activity_main.xml
=> 네이버 맵 관련 런타임 크래시 및 바텀 네비바 UI 겹침 이슈 대응

app/src/main/java/com/runnect/runnect/presentation/discover/adapter/BannerAdapter.kt
=> ArithmeticException 방어 처리
