app/src/main/AndroidManifest.xml
app/src/main/java/com/example/runnect/presentation/mypage/MyHistoryActivity.kt
app/src/main/res/drawable/history_iv_radius_9_22dp.xml
app/src/main/res/drawable/radius_9_22dp.xml
app/src/main/res/layout/activity_my_history.xml
app/src/main/res/layout/item_mypage_history.xml
app/src/main/res/values/colors.xml

#8 [UI] 마이페이지 활동 기록
마이페이지 활동 기록 ui 
이슈 참고 바람

#8 [UI] 마이페이지 활동 기록

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/runnect/presentation/mypage/MyHistoryActivity.kt
app/src/main/java/com/example/runnect/presentation/mypage/MyUploadActivity.kt
app/src/main/res/drawable/history_iv_radius_9_22dp.xml
app/src/main/res/drawable/radius_5dp.xml
app/src/main/res/drawable/radius_9_22dp.xml
app/src/main/res/layout/activity_my_history.xml
app/src/main/res/layout/activity_my_upload.xml
app/src/main/res/layout/item_mypage_history.xml
app/src/main/res/layout/item_mypage_upload.xml
app/src/main/res/values/colors.xml

#7 마이페이지 업로드 코스
마이페이지 업로드 코스 UI 작업
이슈 참고 바람

UI/7 마이페이지 업로드 코스

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/runnect/runnect/data/api/KCourseService.kt
app/src/main/java/com/runnect/runnect/data/model/DetailToRunData.kt
app/src/main/java/com/runnect/runnect/data/model/DrawToRunData.kt
app/src/main/java/com/runnect/runnect/data/model/MyDrawToRunData.kt
app/src/main/java/com/runnect/runnect/data/model/RequestPostRecordDto.kt
app/src/main/java/com/runnect/runnect/data/model/RunToEndRunData.kt
app/src/main/java/com/runnect/runnect/presentation/MainActivity.kt
app/src/main/java/com/runnect/runnect/presentation/countdown/CountDownActivity.kt
app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
app/src/main/java/com/runnect/runnect/presentation/draw/DrawViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/endrun/EndRunActivity.kt
app/src/main/java/com/runnect/runnect/presentation/endrun/EndRunViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
app/src/main/java/com/runnect/runnect/presentation/run/RunActivity.kt
app/src/main/java/com/runnect/runnect/presentation/run/RunViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageMyDrawFragment.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageScrapFragment.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/storage/adapter/StorageScrapAdapter.kt
app/src/main/res/layout/activity_scrap_detail.xml

#35 페이지 연결
이슈 참고 바람.
그런데 상세페이지 시작하기 연결은 마무리 못지었음.
마지막으로 올린 커밋 메세지 확인 바람.

Refactor/35 페이지 연결 

---

app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
app/src/main/java/com/runnect/runnect/presentation/discover/load/DiscoverLoadActivity.kt
app/src/main/java/com/runnect/runnect/presentation/discover/upload/DiscoverUploadActivity.kt
app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
app/src/main/java/com/runnect/runnect/presentation/draw/DrawViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/endrun/EndRunActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/MyPageFragment.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/history/MyHistoryActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/reward/MyRewardActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadActivity.kt
app/src/main/java/com/runnect/runnect/presentation/search/SearchActivity.kt
app/src/main/java/com/runnect/runnect/presentation/search/adapter/SearchAdapter.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageMyDrawFragment.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageScrapFragment.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/storage/adapter/StorageScrapAdapter.kt
app/src/main/java/com/runnect/runnect/util/callback/ItemCount.kt
app/src/main/java/com/runnect/runnect/util/callback/OnSearchClick.kt

#42 [Refactor] 로딩뷰추가외2건 브랜치 PR 피드백 반영
- Failure 시 로딩뷰 invisible 처리
- SearchActivity 화면 깜빡임 해결
- 스크랩 전부 취소 시 empty view 뜨게 수정
최초 로딩 시 리사이클러뷰에 공백 생김
https://user-images.githubusercontent.com/89737271/222346482-50c42f70-0355-400d-b6ae-dfe271c1398d.mp4

Refactor/42 로딩뷰추가외2건 브랜치 PR 피드백 반영

---

app/src/main/java/com/runnect/runnect/presentation/countdown/CountDownActivity.kt
app/src/main/java/com/runnect/runnect/presentation/departure/DepartureActivity.kt
app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
app/src/main/java/com/runnect/runnect/presentation/endrun/EndRunActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/history/adapter/MyHistoryAdapter.kt
app/src/main/java/com/runnect/runnect/presentation/run/RunActivity.kt
app/src/main/java/com/runnect/runnect/presentation/search/SearchActivity.kt
app/src/main/res/layout/fragment_storage_scrap.xml
app/src/main/res/layout/item_mypage_history.xml
app/src/main/res/layout/item_storage_my_draw.xml

#50 QA준비
- 뒤로 가기 터치 시 애니메이션 적용
- 활동 기록 텍스트 정렬 조정
일단 여기까지 하고 이슈에 적어놓은 나머지 사항들은 QA 이후에 작업 계획

Refactor/50 QA준비

---

app/src/main/res/layout/item_mypage_history.xml

#59 활동 기록 item radius 추가
활동 기록 item radius 추가

UI/59 활동 기록 item radius 추가

---

app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
app/src/main/java/com/runnect/runnect/presentation/discover/adapter/CourseRecommendAdapter.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/history/MyHistoryActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/history/MyHistoryViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/history/adapter/MyHistoryAdapter.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/reward/adapter/MyRewardAdapter.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/upload/adapter/MyUploadAdapter.kt
app/src/main/res/layout/activity_my_history.xml

#57 이미지 로딩 딜레이 개선
이미지 로딩 딜레이 개선
한꺼번에 많은 썸네일 이미지를 보여주는 grid recycler view 위주로 개선
Coil -> Glide Migration 및 픽셀 포맷 변경 ARGB_8888 -> RGB_565(목표보상은 ARGB_8888 유지)
Glide thumbnail 추가

Refactor/57 이미지 로딩 딜레이 개선

---

app/src/main/java/com/runnect/runnect/data/dto/CourseDetailDTO.kt
app/src/main/java/com/runnect/runnect/data/dto/response/ResponseCourseDetail.kt
app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailViewModel.kt
app/src/main/java/com/runnect/runnect/util/extension/ResponseExt.kt

#68 course detail DTO 수정
코스 상세 페이지 API 수정사항 반영(경로 데이터 추가)
ResponseCourseDetail 수정
course detail DTO 수정
확장함수 수정

Refactor/68 course detail DTO 수정

---

app/src/main/java/com/runnect/runnect/presentation/countdown/CountDownActivity.kt
app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailViewModel.kt

이 부분만을 위해 이슈 만드는 건 낭비 같아서 안 만들고 브랜치만 만들었음.
커밋 메세지에 자세히 적어놨는데 api가 수정됨에 따라 해당 부분을 클라이언트에도 반영을 해주었음. 구체적으로, api에서 path도 받아올 수 있게됨에 따라 그 path를 포함한 여러 data들을 CountDownActivity로 넘겨서 이후 페이지들과도 연결될 수 있게 해주었음.

스크랩 상세페이지 path 전달

---

app/src/main/java/com/runnect/runnect/data/dto/response/ResponseMyCourseLoad.kt
app/src/main/java/com/runnect/runnect/presentation/discover/load/DiscoverLoadActivity.kt
app/src/main/java/com/runnect/runnect/presentation/discover/load/DiscoverLoadViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/discover/load/adapter/DiscoverLoadAdapter.kt
app/src/main/java/com/runnect/runnect/presentation/discover/upload/DiscoverUploadActivity.kt
app/src/main/java/com/runnect/runnect/util/extension/ResponseExt.kt
app/src/main/res/layout/activity_discover_load_select.xml
app/src/main/res/layout/activity_discover_upload.xml
app/src/main/res/values/strings.xml

#76 코스발견 - 업로드 할 코스 불러오기 뷰 및 업로드 뷰 작업
- 헤더가 machineId에서 accessToken, refreshToken으로 바뀜에 따라 Response 데이터 id도 변경
- 코스 불러오기 시, 코스 name nullable처리
- 코스추천 - 불러오기 뷰 selection 문제 해결
- 불러올 코스가 없을 때 관련 안내 및 코스 그리기 버튼 추가
- 코스 업로드 작성 중 뒤로 가기 시, 코스 선택 해제
- 코스 업로드 제목 inputType 지정
- 업로드 완료 시 코스 발견으로 돌아오도록 구현

Feature/76 코스발견 - 업로드 할 코스 불러오기 뷰 및 업로드 뷰 작업

---

app/src/main/java/com/runnect/runnect/data/dto/response/ResponseMyStamp.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/MyPageFragment.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/reward/MyRewardActivity.kt
app/src/main/java/com/runnect/runnect/util/extension/ContextExt.kt

#82 마이페이지 목표 보상 뷰 작업
machine id Response 수정
getProfileStamp메소드 이름 변경(getStampResId) 및 확장함수로 만들기
스탬프 획득 조건변경

Feature/82 마이페이지 목표 보상 뷰 작업

---

app/src/main/res/layout/activity_my_history_detail.xml

#98  러닝 기록 상세 뷰 Ui 수정
구분선 두께 수정

Fix/98 러닝 기록 상세 뷰 Ui 수정

---

app/src/main/java/com/runnect/runnect/data/api/PCourseService.kt
app/src/main/java/com/runnect/runnect/data/dto/request/RequestUpdatePublicCourse.kt
app/src/main/java/com/runnect/runnect/data/dto/response/ResponseUpdatePublicCourse.kt
app/src/main/java/com/runnect/runnect/data/repository/CourseRepositoryImpl.kt
app/src/main/java/com/runnect/runnect/data/source/remote/CourseDataSource.kt
app/src/main/java/com/runnect/runnect/domain/CourseRepository.kt
app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/history/detail/MyHistoryDetailActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/upload/adapter/MyUploadAdapter.kt
app/src/main/java/com/runnect/runnect/util/extension/ContextExt.kt
app/src/main/res/drawable-xxxhdpi/check_box_selector.xml
app/src/main/res/layout/activity_course_detail.xml
app/src/main/res/layout/item_mypage_upload.xml

#100 마이페이지 업로드한 코스 상세 페이지 작업
업로드 한 코스 뷰 체크박스 구현
어느 뷰에서 왔는 지에 따라 다른 bottomsheet 표시 구현
삭제 기능 구현
수정모드일 때 레이아웃 변형 작업
- 하단 완료하기 버튼 visible
- 시작하기, 스크랩 버튼 invisible
- 프로필 바 invisible
- 내용 입력 창 색상 변경
수정기능 구현
수정 중 뒤로가기 버튼 시 이벤트 구현
- 수정 이력이 있을 시 -> 현재 액티비티 종료 및 업로드 코스 목록을 새로 불러오기
- 수정 이력이 없을 시 -> 현재 액티비티 종료
https://github.com/Runnect/Runnect-Android/assets/70442964/8c7a0e46-aabd-4c0f-bada-1bbaa061b16f

Feature/100 마이페이지 업로드한 코스 상세 페이지 작업

---

app/src/main/java/com/runnect/runnect/presentation/MainActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/MyPageFragment.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/setting/MySettingFragment.kt
app/src/main/res/layout/activity_my_history.xml
app/src/main/res/layout/fragment_my_setting.xml
app/src/main/res/values/strings.xml

#103 마이페이지 설정 메인뷰 작업
레이아웃 작성
마이페이지 -> 설정 메인 뷰 전환 구현

Feature/103 마이페이지 설정 메인뷰 작업

---

app/src/main/java/com/runnect/runnect/presentation/MainActivity.kt
app/src/main/java/com/runnect/runnect/presentation/countdown/CountDownActivity.kt
app/src/main/java/com/runnect/runnect/presentation/coursemain/CourseMainFragment.kt
app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
app/src/main/java/com/runnect/runnect/presentation/discover/adapter/CourseRecommendAdapter.kt
app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
app/src/main/java/com/runnect/runnect/presentation/endrun/EndRunActivity.kt
app/src/main/java/com/runnect/runnect/presentation/login/LoginActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/MyPageFragment.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/editname/MyPageEditNameActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/history/MyHistoryActivity.kt
app/src/main/java/com/runnect/runnect/presentation/run/RunActivity.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageMainFragment.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageMyDrawFragment.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageScrapFragment.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageViewModel.kt
app/src/main/res/layout/activity_count_down.xml
app/src/main/res/layout/activity_my_history.xml
app/src/main/res/layout/fragment_storage_scrap.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

이슈 안 만들었음
전반적으로 QA 리스트에 있는 것들 반영함.
향후 더 추가될 수도 있음

[fix] 1차 릴리즈 QA 반영

---

app/src/main/java/com/runnect/runnect/util/extension/ContextExt.kt

#116 머지 충돌 해결
ContextExt 머지 충돌 해결

[Fix] 머지 충돌 해결

---

app/src/main/res/layout/activity_course_detail.xml
app/src/main/res/layout/activity_discover_load_select.xml
app/src/main/res/layout/activity_discover_search.xml
app/src/main/res/layout/activity_discover_upload.xml
app/src/main/res/layout/activity_draw.xml
app/src/main/res/layout/activity_my_draw_detail.xml
app/src/main/res/layout/activity_my_history.xml
app/src/main/res/layout/activity_my_history_detail.xml
app/src/main/res/layout/activity_my_page_edit_name.xml
app/src/main/res/layout/activity_my_reward.xml
app/src/main/res/layout/activity_my_upload.xml
app/src/main/res/layout/activity_scrap_detail.xml
app/src/main/res/layout/custom_dialog_delete.xml
app/src/main/res/layout/custom_dialog_make_course.xml
app/src/main/res/layout/custom_dialog_report.xml
app/src/main/res/layout/custom_dialog_require_login.xml
app/src/main/res/layout/fragment_course_main.xml
app/src/main/res/layout/fragment_discover.xml
app/src/main/res/layout/fragment_my_setting.xml
app/src/main/res/layout/fragment_my_setting_account_info.xml

#119 버튼 및 툴바 고정 dp로 수정
height를 고정 dp로 주기로 함. 이에 수정 작업을 하였음.

#119 [fix] 버튼 및 툴바 고정 dp로 수정

---

app/src/main/java/com/runnect/runnect/presentation/mypage/setting/MySettingFragment.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/setting/accountinfo/MySettingAccountInfoFragment.kt
app/src/main/res/layout/fragment_my_page.xml
app/src/main/res/layout/fragment_my_setting.xml
app/src/main/res/layout/fragment_my_setting_account_info.xml

#123 설정 및 계정정보 뒤로가기 로직 구현
- 설정 기기 뒤로가기 로직 추가
- 계정정보 기기 뒤로가기 로직 추가
- under stroke가 적용되지 않는 오류 해결

Fix/123 설정 및 계정정보 뒤로가기 로직 구현

---

app/src/main/java/com/runnect/runnect/presentation/login/LoginActivity.kt
app/src/main/res/layout/activity_login.xml

버튼으로 만드니까 눌렀을 때 아이콘이 숨겨지는 이슈가 있어서 카드뷰로 수정하였음
#130 소셜 로그인 버튼 카드뷰로 수정
소셜 로그인 버튼 카드뷰로 수정

#130 [fix] 소셜 로그인 버튼 카드뷰로 수정

---

app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
app/src/main/java/com/runnect/runnect/presentation/discover/adapter/CourseRecommendAdapter.kt
app/src/main/java/com/runnect/runnect/util/CustomToast.kt
app/src/main/res/drawable-v24/custom_toast.xml
app/src/main/res/layout/custom_toast.xml
app/src/main/res/layout/item_discover_course_info.xml
app/src/main/res/values/colors.xml

Fix/125 방문자모드러닝금지

---

app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt

#132 코스발견 - 코스 상세 페이지에서 스크랩 후 기기 뒤로가기 버튼 클릭 시 반영되지 않는 이슈
onBackPressed 삭제

Fix/132 코스발견 - 코스 상세 페이지에서 스크랩 후 기기 뒤로가기 버튼 클릭 시 반영되지 않는 이슈

---

app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
app/src/main/res/layout/activity_search.xml
app/src/main/res/layout/fragment_my_page.xml

색상 코드 값을 그대로 입력했는데 피그마에서랑 안스에서랑 색감이 다름.
원인을 찾아보니 Divider는 색상을 background 속성에서 지정하면 안 되고 dividerColor라는 속성에서 지정을 해줘야 잘 적용이 되는 거였음
#134 [fix] Divider 색상 수정
Divider 색상 수정

#134 [fix] Divider 색상 수정

---

app/src/main/res/layout/activity_end_run.xml
app/src/main/res/layout/fragment_my_page.xml
app/src/main/res/layout/fragment_my_setting.xml

#140 구분선 색상 변경
- 러닝종료 기록 뷰 구분선
- 마이페이지 각 항목 프레임 밑 구분선
- 설정 뷰 툴바 및 항목 구분선

Fix/140 구분선 색상 변경

---

app/src/main/java/com/runnect/runnect/presentation/mypage/history/detail/MyHistoryDetailActivity.kt

#143 뒤로가기 버튼 콜백 수정
기록 상세페이지 뒤로가기 버튼 클릭 시, 수정 사항 반영

Fix/143 기록 상세페이지 뒤로가기 버튼 클릭 시, 수정 사항 반영

---

app/src/main/java/com/runnect/runnect/presentation/discover/load/DiscoverLoadActivity.kt
app/src/main/res/layout/activity_discover_load_select.xml

#145 코스 불러오기 뷰 진입 시 선택하기 버튼이 사라지지 않는 이슈
불러올 코스가 없을 시 '선택하기' 버튼 invisible

Fix/145 코스 불러오기 뷰 '선택하기' 버튼 visible 추가

---

app/src/main/java/com/runnect/runnect/presentation/login/KakaoLogin.kt

#147 카카오톡 로그인 이슈
카카오톡이 이미 설치되어있는 경우 로그인되지 않는 이슈 해결
=> 실기기에서는 카카오 로그인이 안되었던 이유

Fix/147 카카오톡 로그인 이슈 해결

---

app/src/main/java/com/runnect/runnect/presentation/discover/upload/DiscoverUploadActivity.kt

#149 코스업로드 완료 후 코스 발견에 반영되지 않는 이슈
[Fix] 코스 업로드 완료 후 코스 발견에 반영되도록 구현
https://github.com/Runnect/Runnect-Android/assets/70442964/b5d72576-1747-4f96-970c-d0555ed1c314

Fix/149 코스업로드 완료 후 코스 발견에 반영되지 않는 이슈

---

app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadActivity.kt
app/src/main/java/com/runnect/runnect/util/extension/ResponseExt.kt

#155 업로드한 코스 페이지 삭제버튼 활성화 오류 수정
147번 라인 복구

Fix/업로드한 코스 페이지 삭제버튼 활성화 오류 수정

---

app/build.gradle
app/src/main/java/com/runnect/runnect/application/EncryptedSharedPreferenceWorkaround.kt
app/src/main/java/com/runnect/runnect/application/PreferenceManager.kt
app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
app/src/main/java/com/runnect/runnect/presentation/discover/search/DiscoverSearchActivity.kt
app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/MyPageFragment.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageMainFragment.kt
app/src/main/res/layout/item_mypage_upload.xml

Fix/160 encrypted sp tink 초기화 이슈 예외처리
- EncryptedSharedPreferences 버전 수정
- 코스 생성 동기 처리
- 업로드 코스 -> 상세페이지 통신 에러 해결
- 방문자모드 -> 로그인 전환 시 뷰 finish()
- 업로드한 코스 item 제목 초과되는 이슈 해결

Fix/160 encrypted sp tink 초기화 이슈 예외처리

---

app/src/main/java/com/runnect/runnect/application/ApplicationClass.kt

#164 다크모드제한 
디바이스 자체에 다크모드가 적용되어 앱이 실행되는 경우 사용자가 서비스를 원활히 사용할 수 없어서 다크모드를 제한해주었음

[setting] 다크모드 제한

---

app/src/main/java/com/runnect/runnect/di/RepositoryModule.kt
app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverPromotionAdapter.kt

#173 RepositoryModule (@Provides -> @Binds)
@Provides를 꼭 써야하는 이유가 없는 상황에서 @Binds를 쓰는 게 더 간결하고 di를 위한 코드를 덜 생성한다는 측면에서 기존에 @Provides로 짜놨던 코드를 @Binds를 쓰는 것으로 수정을 진행하였습니다.

[refactor] RepositoryModule (@Provides -> @Binds)

---

app/src/main/java/com/runnect/runnect/presentation/MainActivity.kt
app/src/main/java/com/runnect/runnect/presentation/countdown/CountDownActivity.kt
app/src/main/java/com/runnect/runnect/presentation/coursemain/CourseMainFragment.kt
app/src/main/java/com/runnect/runnect/presentation/coursemain/CourseMainViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
app/src/main/java/com/runnect/runnect/presentation/discover/adapter/CourseRecommendAdapter.kt
app/src/main/java/com/runnect/runnect/presentation/discover/load/DiscoverLoadActivity.kt
app/src/main/java/com/runnect/runnect/presentation/discover/load/adapter/DiscoverLoadAdapter.kt
app/src/main/java/com/runnect/runnect/presentation/discover/search/adapter/DiscoverSearchAdapter.kt
app/src/main/java/com/runnect/runnect/presentation/discover/upload/DiscoverUploadActivity.kt
app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
app/src/main/java/com/runnect/runnect/presentation/endrun/EndRunActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
app/src/main/java/com/runnect/runnect/presentation/run/RunActivity.kt
app/src/main/java/com/runnect/runnect/presentation/search/SearchActivity.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageMainFragment.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageMyDrawFragment.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageScrapFragment.kt
app/src/main/java/com/runnect/runnect/presentation/storage/adapter/StorageScrapAdapter.kt

#176 매직 리터럴 -> 상수
전반적으로 가독성이 떨어지는 부분들에 대하여 리팩토링을 진행해주었습니다.
- 문자열 포매팅을 활용한 timer 바인딩 코드 간결화
- 코틀린 가이드를 따르도록 변수 이름 수정
- 함수 단일화로 전체 코드량 줄이고 재사용성 높이기
- if문 중첩 제거 (논리연산자, 라벨, when문, scope 함수 등 활용)
- 매직 리터럴 -> 상수로 변경

Refactor/176 매직리터럴 수정

---

app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverPromotionAdapter.kt

#185 코스 발견 배너 페이지 관련 이슈
DiscoverPromotionAdapter에 존재하는 고정값 FRAME_NUM을 bannerCount로 변경

Fix/185 코스 발견 배너 페이지 관련 이슈

---

app/src/main/java/com/runnect/runnect/presentation/MainActivity.kt
app/src/main/java/com/runnect/runnect/presentation/countdown/CountDownActivity.kt
app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
app/src/main/java/com/runnect/runnect/presentation/discover/load/DiscoverLoadActivity.kt
app/src/main/java/com/runnect/runnect/presentation/discover/search/DiscoverSearchActivity.kt
app/src/main/java/com/runnect/runnect/presentation/discover/upload/DiscoverUploadActivity.kt
app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
app/src/main/java/com/runnect/runnect/presentation/endrun/EndRunActivity.kt
app/src/main/java/com/runnect/runnect/presentation/login/GiveNicknameActivity.kt
app/src/main/java/com/runnect/runnect/presentation/login/LoginActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/MyPageFragment.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/editname/MyPageEditNameActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/history/MyHistoryActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/reward/MyRewardActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/setting/accountinfo/MySettingAccountInfoFragment.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadActivity.kt
app/src/main/java/com/runnect/runnect/presentation/run/RunActivity.kt
app/src/main/java/com/runnect/runnect/presentation/search/SearchActivity.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageMyDrawFragment.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageScrapFragment.kt
app/src/main/java/com/runnect/runnect/util/callback/OnItemClick.kt

리터럴 -> 상수 수정
- key값이 String으로 들어가기 때문에 리터럴로 바로 적으면 오탈자 등의 이슈가 생길 수 있으므로 상수로 빼주었고 네이밍을 EXTRA_로 통일해주었습니다.
- MainActivity에서 쓰이는 getExtra의 key 값을 하나로 통일해 getExtra()를 1번만 호출할 수 있게 수정하였습니다.

Refactor/리터럴 상수 교체

---

app/src/main/java/com/runnect/runnect/data/service/TokenAuthenticator.kt

#194 로그인 토큰 만료 관련 이슈
- 토큰 만료 및 유효하지 않은 토큰에 대한 예외처리
https://github.com/Runnect/Runnect-Android/assets/70442964/d1cf2142-9d27-477a-be12-3052f1c8f911

Fix/194 로그인 토큰 만료 관련 이슈

---

app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
app/src/main/java/com/runnect/runnect/presentation/draw/DrawViewModel.kt
app/src/main/res/layout/fragment_storage_my_draw.xml

#196 리팩토링 과정에서 실수로 constraint를 안 걸어줘서 화면 영역에 안 타나는 이슈를 해결함
SwipeRefreshLayout에 constraint를 주었음

[fix] 내가그린코스 편집 버튼 constraint 추가

---

app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt

#213 코스발견 상단 배너 스크롤 타이머 에러 수정
timerTask 객체의 상태를 검사한 후, task가 중복적으로 schedule 또는 cancel 되지 않도록 구현
scheduledExecutionTime() 메소드를 이용해 task가 이미 예약되었는지, 취소되었는지에 대한 예외처리

[fix] timertask 관련 예외처리 구현

---

app/src/main/java/com/runnect/runnect/presentation/mypage/MyPageFragment.kt
app/src/main/res/layout/fragment_my_page.xml
app/src/main/res/values/strings.xml

closed #220 [FEAT] 카카오톡 채널 문의 구현
- 카카오톡 채널 문의 구현
- 마이페이지 메뉴 size 수정 (360:60 -> 390:62)
- addChannelUrl 말고 channelChatUrl를 써야 카톡 채팅방으로 바로 연결됩니다
https://github.com/Runnect/Runnect-Android/assets/89737271/94e037db-e2cb-4613-88e9-1238cc4212d3

[FEAT] 마이페이지 / 카카오톡 채널 문의 구현

---

app/src/main/res/layout/activity_give_nickname.xml

closed #229 로그인 닉네임 입력창 fontFamily 수정
- EditText fontFamily 수정 (semibold -> medium)

[UI] 로그인-닉네임 입력창 / EditText fontFamily 수정 (semibold -> medium)

---

app/src/main/res/layout/activity_search.xml
app/src/main/res/values/strings.xml

closed #247 [MOD] 출발지 키워드 검색 / EditText 수정 (터치 영역, hintColor, 가이드 문구)
- wrap_content -> 0dp, constraint 수정
- hintColor G3 설정
- 가이드 문구 교체

[MOD] 출발지 키워드 검색 / EditText 수정 (터치 영역, hintColor, 가이드 문구)

---

app/build.gradle
app/src/main/java/com/runnect/runnect/data/dto/CourseData.kt
app/src/main/java/com/runnect/runnect/data/dto/response/ResponsePostCourseDTO.kt
app/src/main/java/com/runnect/runnect/data/dto/response/ResponsePostMyDrawCourse.kt
app/src/main/java/com/runnect/runnect/data/repository/CourseRepositoryImpl.kt
app/src/main/java/com/runnect/runnect/data/service/CourseService.kt
app/src/main/java/com/runnect/runnect/data/source/remote/RemoteCourseDataSource.kt
app/src/main/java/com/runnect/runnect/domain/CourseRepository.kt
app/src/main/java/com/runnect/runnect/presentation/draw/CourseCreateRequestDto.kt
app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
app/src/main/java/com/runnect/runnect/presentation/draw/DrawViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/run/RunActivity.kt

- closed #283  
여러 이슈가 있어서 pr이 늦어졌습니다.
- nginx 문제, 허용 용량 늘리는 것으로 해결하였으나 서버 부담 및 속도 저하 이슈로 추후 압축해서 보내는 방향으로 개선이 필요해보입니다.
- 정확한 개념은 모르지만 안드에서 되는 게 ios에서 안 된다고 해서 둘 다 호환되는 방향으로 서버 개발이 이어지느라 늦어졌습니다. 현재는 둘 다 테스트 완료했고 성공했습니다! 
연결은 했는데 이후 RunActivity로 data를 넘기는 세팅이 아직 덜 됐습니다. 이 부분은 branch를 새로 파서 작업 진행 예정입니다!
- 코스 생성 api에 제목 입력 추가 반영

[FEAT] 코스 그리기 / 코스 생성 API에 제목 입력 추가 반영

---

app/src/main/java/com/runnect/runnect/data/dto/ProfileCourseData.kt
app/src/main/java/com/runnect/runnect/presentation/profile/ProfileActivity.kt
app/src/main/java/com/runnect/runnect/presentation/profile/ProfileCourseAdapter.kt
app/src/main/java/com/runnect/runnect/presentation/profile/ProfileViewModel.kt
app/src/main/res/layout/activity_course_detail.xml
app/src/main/res/layout/activity_profile.xml
app/src/main/res/layout/item_profile_course.xml
app/src/main/res/values/strings.xml

- closed #300 
- 코스 상세페이지 UI 변동사항 반영
- 상세페이지에서 유저 클릭 시 나타나는 프로필 화면 UI 구현
유저 프로필 조회 시 불러오는 '업로드된 코스' 는 서버측에서 페이지가 없어서 nestedScrollView로 구현했고, 리사이클러뷰 아이템 레이아웃은 스크랩 아이템 재활용했습니다! 
그거 제외하곤 간단한 뷰여서 UI 머지 후 화면 전환을 포함한 서버통신 등 기능 개발 들어갈게요 😄  UI 첫 PR인만큼 컨벤션 잘 맞는지도 확인부탁드려요 ~! 
https://github.com/Runnect/Runnect-Android/assets/81434152/cc36a796-c970-4060-9b97-105dd32fa7ec

[UI] 코스 발견 / 상세페이지 프로필 조회 화면 구현

---

app/src/main/java/com/runnect/runnect/application/ApplicationClass.kt
app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
app/src/main/java/com/runnect/runnect/presentation/discover/search/DiscoverSearchActivity.kt
app/src/main/java/com/runnect/runnect/presentation/discover/upload/DiscoverUploadActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/MyPageFragment.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/history/MyHistoryActivity.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/setting/MySettingFragment.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/setting/accountinfo/MySettingAccountInfoFragment.kt
app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadActivity.kt
app/src/main/java/com/runnect/runnect/presentation/profile/ProfileActivity.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageMainFragment.kt
app/src/main/java/com/runnect/runnect/presentation/storage/StorageMyDrawFragment.kt
app/src/main/java/com/runnect/runnect/util/analytics/Analytics.kt
app/src/main/java/com/runnect/runnect/util/analytics/EventName.kt

#315 
마이페이지, 보관함, 코스 발견 이벤트 태깅했습니다 ~
- 회의 내용처럼 bundle은 nullable하게 만들었고, ios와 이벤트명 통일해 작성했습니다 !
- 다만 코스 발견 쪽이 아직 머지안된 PR이 있어서 이슈는 안닫고 일부는 추후 반영하겠습니다
util 함수 필요하실것같아 먼저 PR 올려요

[ADD] 마이페이지, 보관함, 발견 / 이벤트 태깅

---

app/src/main/java/com/runnect/runnect/data/dto/response/ResponseGetMyHistory.kt

- closed #327
서버 Spring으로 마이그레이션하면서 responseDTO 바뀐 게 있는데 반영이 안 돼있었습니다.
id -> userId
- 러닝 기록 api responseDTO 수정  
- 이전 작업자가 responseDTO 만든 방식은 명세에 적혀있는 sample response랑 비교하기 어려운 것 같습니다. 당장 수정하기에는 사이드이펙트가 터질 것 같아서 @SerialName을 달아서 직렬화가 정상적으로 이루어질 수 있게 맵핑만 해주었습니다.

[FIX] 마이페이지 / 러닝 기록 api responseDTO 수정

---

app/src/main/java/com/runnect/runnect/presentation/discover/pick/DiscoverPickActivity.kt
app/src/main/java/com/runnect/runnect/presentation/discover/pick/DiscoverPickViewModel.kt
app/src/main/java/com/runnect/runnect/presentation/discover/pick/adapter/DiscoverPickAdapter.kt

closed #329
코스 업로드 시, 리스트에서 항목은 하나만 선택 가능하도록 수정했습니다. 지피티 덕분에 구현 시간 대폭 줄였네요.. 👍 
관련 기능 명세서 이미지 첨부합니다.

[FIX] 코스 발견 / 내가 그린 코스 업로드 시, 단일 선택만 가능하도록 변경 

---

app/src/main/java/com/runnect/runnect/data/service/AuthInterceptor.kt

- closed #352 
- 이슈 참고해주세요 : ) 
- ResponseInteceptor 생긴 뒤 기존 인터셉터가 로직이 겹칠 수 있으니 한번더 확인했어야됐는데 그걸 못했네요 😂
- 서버팀에게 테스트서버 만료시간 1분으로 줄여달라고 요청한뒤 해결 완료 확인했습니다 !

[FIX] 토큰 재발급 시 앱 크래시 현상 해결

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/runnect/runnect/presentation/composesample/ComposeSampleActivity.kt
app/src/main/java/com/runnect/runnect/presentation/composesample/ui/theme/Color.kt
app/src/main/java/com/runnect/runnect/presentation/composesample/ui/theme/Theme.kt
app/src/main/java/com/runnect/runnect/presentation/composesample/ui/theme/Type.kt
app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
build.gradle

[ADD] 컴포즈 의존성 추가

---

app/build.gradle
build.gradle

파이어베이스 crashlytics sdk 추가
